quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/books20262026
quarkus.datasource.username=postgres
quarkus.datasource.password=labcom,2015

quarkus.flyway.actions=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
