CREATE TABLE authors (
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

INSERT INTO authors (name) VALUES ('Jorge Luis Borges');
INSERT INTO authors (name) VALUES ('Gabriel García Márquez');
INSERT INTO authors (name) VALUES ('Isabel Allende');
