(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

insert into authors (name) values ('Jorge Luis Borges');
insert into authors (name) values ('Gabriel García Márquez');
insert into authors (name) values ('Isabel Allende');
 